ML/urls.py
from django.contrib import admin
from django.urls import path, include

from BoxDiet.views import DashboardView, UsersView, UserDetailsView, MealView, MealDetailsView, UserCreateView, RankCreateView, SignUp

urlpatterns = [
    path('admin/', admin.site.urls, name='test'),
    path('', DashboardView.as_view(), name='dashboard'),
    path("user-list/", UsersView.as_view(), name='user_list'),
    path("meal-list/", MealView.as_view(), name='meal_list'),
    path('user-details/<int:pk>', UserDetailsView.as_view(), name='user_detail'),
    path('meal-details/<int:pk>', MealDetailsView.as_view(), name='meal_detail'),
    path('user-create/', UserCreateView.as_view(), name='user_create'),
    path('rank-create/', RankCreateView.as_view(), name='rank_create'),
    path('API/', include('RestAPI.urls')),
    path('box/', include('django.contrib.auth.urls')),
    path('signup/', SignUp.as_view(), name='signup'),


]

BoxDiet/models.py
from django.db import models

# Create your models here.
from django.db.models import Avg, Count


class User(models.Model):
    SEX = (
        ('w', 'Kobieta '),
        ('m', 'Mężczyzna'),
        ('\\N', "Brak danych"),
    )
    id = models.AutoField(primary_key=True)
    sex = models.CharField(max_length=2, choices=SEX, verbose_name="Płeć")

    def avg_of_given_ranks(self):
        # returns None if no rank is related to this instance
        temp = self.meals_user.aggregate(Avg('mark'))
        if temp['mark__avg'] is None:
            return 0.0
        return float(temp['mark__avg'])

    def no_of_given_ranks(self):
        # returns None if no rank is related to this instance
        return self.meals_user.aggregate(Count('mark'))

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return str(self.id)


class Meal(models.Model):
    meal_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=246)
    average_rank = models.FloatField(null=True, default=None)
    no_of_ranks = models.IntegerField(null=True, default=0)
    calories_summary = models.FloatField()
    price_summary = models.FloatField()
    fat_summary = models.FloatField()
    protein_summary = models.FloatField()
    carbohydrates_summary = models.FloatField()
    cellulose_summary = models.FloatField()

    class Meta:
        ordering = ["-average_rank"]

    def __str__(self):
        return self.name

    def avg_of_given_ranks(self):
        temp = self.meals_user.aggregate(Avg('mark'))
        if temp['mark__avg'] is None:
            return 0.0
        return float(temp['mark__avg'])

    def no_of_given_ranks(self):
        # returns None if no rank is related to this instance
        return self.meals_user.aggregate(Count('mark'))


class Rank(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE, related_name="meals_user")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="meals_user")
    mark = models.FloatField()

    def save(self, *args, **kwargs):
        try:
            meal_id = self.meal_id
            meal = Meal.objects.get(meal_id=meal_id)
            meal.average_rank = meal.avg_of_given_ranks()
            meal.no_of_ranks = meal.no_of_given_ranks()['mark__count']
            meal.save()
            r = super(Rank, self).save()
        except Meal.DoesNotExist:
            r = super(Rank, self).save()
        return r

    class Meta:
        ordering = ["user_id"]

class Recommended(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE, related_name="recommended")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recommended")
    predicted_mark = models.FloatField(null=True)

    class Meta:
        ordering = ["user_id"]

BoxDiet/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView
from django.views import View
from django.views import generic

from BoxDiet.models import Meal, User, Rank, Recommended
from BoxDiet.utils import count, sliced_paginator


class DashboardView(LoginRequiredMixin, View):
    def get(self, request):
        meals_no = count(Meal)
        users_no = count(User)
        ranks_no = count(Rank)
        top10meals = Meal.objects.filter(average_rank__gt=4.6).order_by('-no_of_ranks')[:10]
        worst10meals = Meal.objects.filter(average_rank__lte=2.9).order_by('-no_of_ranks')[:10]
        return render(request, 'BoxDiet/dashboard.html', {'meals_no': meals_no, 'ranks_no': ranks_no,
                                                          'users_no': users_no, 'top10meals': top10meals,
                                                          'worst10meals': worst10meals})


class UsersView(LoginRequiredMixin, View):

    def get(self, request, searched_name=""):
        searched_name = request.GET.get('searched_name')
        if searched_name == "" or searched_name is None:
            object_list = User.objects.order_by('-id')
            page_range, object_list = sliced_paginator(request, object_list)
        else:
            object_list = self.search_user(searched_name)
            page_range, object_list = sliced_paginator(request, object_list)
        return render(request, 'BoxDiet/user_list.html',
                      {"object_list": object_list, 'page_range': page_range, "searched_name": searched_name})

    def search_user(self, searched_name):
        try:
            searched_name = int(searched_name)
            object_list = User.objects.filter(id=searched_name)
        except ValueError:
            lower_gender = searched_name.lower()
            if lower_gender in 'kobieta':
                object_list = User.objects.filter(sex__iexact='w')
            elif lower_gender in 'mężczyzna':
                object_list = User.objects.filter(sex__iexact='m')
            else:
                object_list = User.objects.filter(sex__iexact='\\n')
        return object_list


class MealView(LoginRequiredMixin, View):

    def get(self, request, searched_name=""):
        searched_name = request.GET.get('searched_name')
        if searched_name == "" or searched_name is None:
            object_list = Meal.objects.order_by('-average_rank').order_by('-no_of_ranks')
            page_range, object_list = sliced_paginator(request, object_list)
        else:
            object_list = self.search_meal(searched_name)
            page_range, object_list = sliced_paginator(request, object_list)
        return render(request, 'BoxDiet/meal_list.html',
                      {"object_list": object_list, 'page_range': page_range, "searched_name": searched_name})

    def search_meal(self, searched_name):
        try:
            searched_name = int(searched_name)
            object_list = Meal.objects.filter(meal_id=searched_name).order_by(
                '-average_rank').order_by('-no_of_ranks')
        except ValueError:
            object_list = Meal.objects.filter(name__icontains=searched_name).order_by(
                '-average_rank').order_by(
                '-no_of_ranks')
        return object_list


class UserDetailsView(LoginRequiredMixin, DetailView):
    model = User

    def get_context_data(self, **kwargs):
        context = super(UserDetailsView, self).get_context_data(**kwargs)
        recs = Recommended.objects.filter(user__id=self.kwargs['pk']).order_by('meal_id')
        context['recs'] = recs
        return context


class UserCreateView(LoginRequiredMixin, CreateView):
    model = User
    fields = ['sex']
    success_url = reverse_lazy('user_list')


class RankCreateView(LoginRequiredMixin, View):
    def get(self, request):
        users = User.objects.all()
        meals = Meal.objects.all()
        return render(request, "BoxDiet/rank_form.html",
                      {'users': users, 'meals': meals})

    def post(self, request):
        user_id = request.POST.get('user')
        meal_id = request.POST.get('meal')
        mark = request.POST.get('mark')
        form = 'BoxDiet/rank_form.html'
        users = User.objects.all()
        meals = Meal.objects.all()

        try:
            if int(mark) in range(1, 6):
                rank = Rank.objects.create(user_id=user_id, meal_id=meal_id, mark=mark)
            else:
                message = "Nie zapisano do bazy. Wybierz ocenę od 1 do 5."
                return render(request, form, {'message': message, 'users': users, 'meals': meals})
        except:
            message = "Podaj poprawne dane!"
            return render(request, form, {'message': message, 'users': users, 'meals': meals})
        return render(request, form,
                      {'users': users, 'meals': meals, 'message': f'Dodano ocenę {rank.mark} dla dania {rank.meal}'})


class MealDetailsView(LoginRequiredMixin, DetailView):
    model = Meal


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

BoxDiet/templates/BoxDiet/__base__.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %} | Box Diet</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Charmonman:400,700|Open+Sans:400,600,700&amp;subset=latin-ext"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static "BoxDiet/css/style.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'BoxDiet/images/favicon.ico' type='image/x-icon' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

</head>

<body>

    <header class="page-header">
        <nav class="navbar navbar-expand-lg justify-content-between">
            <a href="/" class="navbar-brand main-logo main-logo-smaller">
               Recommend  <span>MEal</span>
            </a>
         <div class="d-flex justify-content-around">
             <h4 class="text-light mr-3 mt-1">{{ user.username }}</h4>
             <div class="circle-div text-center mr-1"><i class="fas fa-user icon-user"></i></div>
             {% if user.is_authenticated %}
             <a class="btn btn-color p-1 ml-3" href="{% url 'logout' %}">Wyloguj się</a>
             {% endif %}
         </div>

        </nav>
    </header>

    <section class="dashboard-section">
        <div class="row dashboard-nowrap">
                <ul class="nav flex-column long-bg">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'dashboard' %}">
                                <span>Pulpit</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user_list' %}">
                                <span>Klienci diety</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'meal_list' %}">
                                <span>Posiłki</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <!-- Podstrony związane z zarządzaniem użytkownikami
                        <li class="nav-item">
                            <a class="nav-link" href="">
                                <span>Edytuj dane</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="">
                                <span>Zmień hasło</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">
                                <span>Użytkownicy</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        -->
                    </ul>

            <div class="m-4 p-3 width-medium text-color-darker">
                {% if message %}
                    <h3>{{ message }}</h3>
                {% endif %}

<!-- //--------------------------- page content -------------------------// -->
{% block content %}{% endblock content %}
<!-- //--------------------------- page content end ---------------------// -->

            </div>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
{% load static %}
</body>
</html>

BoxDiet/templates/BoxDiet/dashboard.html
{% extends "BoxDiet/__base__.html" %}
{% block title %}{% endblock title %}
{% block content %}
    <div class="dashboard-header m-4">
        <div class="dashboard-menu">
            <div class="menu-item border-dashed">
                <a href="{% url 'user_create' %}">
                    <i class="far fa-plus-square icon-plus-square"></i>
                    <span class="title">dodaj Klienta</span>
                </a>
            </div>

            <div class="menu-item border-dashed">
                <a href="{% url 'rank_create' %}">
                    <i class="far fa-plus-square icon-plus-square"></i>
                    <span class="title">dodaj ocenę posiłku</span>
                </a>
            </div>
        </div>

        <div class="dashboard-alerts">
            <div class="alert-item alert-info">
                <i class="fas icon-circle fa-info-circle"></i>
                <span class="font-weight-bold"><a href="{% url 'meal_list' %}" style="text-decoration:none"> Liczba posiłków: {{ meals_no }}</a></span>
            </div>
            <div class="alert-item alert-light">
                <i class="far icon-calendar fa-user"></i>
                <span class="font-weight-bold"><a href="{% url 'user_list' %}" style="text-decoration:none">Liczba Klientów: {{ users_no }}</a></span>
            </div>
                        <div class="alert-item alert-light">
                <i class="far icon-user fa-list-alt"></i>
                <span class="font-weight-bold"><a href="" style="text-decoration:none">Liczba ocen: {{ ranks_no }}</a></span>
            </div>
        </div>
    </div>
    <div class="m-4 p-4 border-dashed">
        <h2 class="dashboard-content-title">
            <span>Najlepiej oceniane posiłki:</span><a href="" style="text-decoration:none"> {{ last_plan.name }}</a>
        </h2>
        <div class="schedules-content">
            <table class="table border-bottom">
                <thead>
                <tr class="d-flex">
                    <th class="col-1">ID</th>
                    <th class="col-5">Nazwa</th>
                    <th class="col-2">Średnia</th>
                    <th class="col-2">Liczba ocen</th>
                    <th class="col-2 center">Akcje</th>
                </tr>
                </thead>
                <tbody class="text-color-lighter">


                {% for meal in top10meals %}
                    <tr class="d-flex">
                        <td class="col-1">{{ meal.meal_id }}</td>
                        <td class="col-5">
                            {{ meal.name }}
                        </td>
                        <td class="col-2">
                            {% if meal.average_rank %}{{ meal.average_rank|floatformat }}
                            {% else %} Brak ocen {% endif %}
                        <td class="col-2">
                            {% if meal.no_of_given_ranks.mark__count %}{{ meal.no_of_given_ranks.mark__count }}
                            {% else %} Brak ocen {% endif %}
                        <td class="col-2 d-flex align-items-center justify-content-center flex-wrap">
                            {#                            <a href="#" class="btn btn-danger rounded-0 text-light m-1">Usuń</a>#}
                            <a href="{% url 'meal_detail' pk=meal.meal_id %}"
                               class="btn btn-info rounded-0 text-light m-1">Szczegóły</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    <table>
        <h2 class="dashboard-content-title">
            <span>Najgorzej oceniane posiłki:</span><a href="" style="text-decoration:none"> {{ last_plan.name }}</a>
        </h2>

        <div class="schedules-content">
            <table class="table border-bottom">
                <thead>
                <tr class="d-flex">
                    <th class="col-1">ID</th>
                    <th class="col-5">Nazwa</th>
                    <th class="col-2">Średnia</th>
                    <th class="col-2">Liczba ocen</th>
                    <th class="col-2 center">Akcje</th>
                </tr>
                </thead>
                <tbody class="text-color-lighter">


                {% for meal in worst10meals %}
                    <tr class="d-flex">
                        <td class="col-1">{{ meal.meal_id }}</td>
                        <td class="col-5">
                            {{ meal.name }}
                        </td>
                        <td class="col-2">
                            {% if meal.average_rank %}{{ meal.average_rank|floatformat }}
                            {% else %} Brak ocen {% endif %}
                        <td class="col-2">
                            {% if meal.no_of_given_ranks.mark__count %}{{ meal.no_of_given_ranks.mark__count }}
                            {% else %} Brak ocen {% endif %}
                        <td class="col-2 d-flex align-items-center justify-content-center flex-wrap">
                            {#                            <a href="#" class="btn btn-danger rounded-0 text-light m-1">Usuń</a>#}
                            <a href="{% url 'meal_detail' pk=meal.meal_id %}"
                               class="btn btn-info rounded-0 text-light m-1">Szczegóły</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
{% endblock content %}

BoxDiet/templates/BoxDiet/rank_form.html
{% extends "BoxDiet/__base__.html" %}

{% block title %}{% endblock title %}
{% block content %}
    <div class="dashboard-content border-dashed p-3 m-4 view-height">

        <div class="row border-bottom border-3 p-1 m-1">
            <div class="col noPadding">
                <h3 class="color-header text-uppercase"> Nowa ocena</h3>
            </div>
            <div class="col d-flex justify-content-end mb-2 noPadding">
                <form method="post">
                    {% csrf_token %}
                <button type="submit"
                        class="btn btn-color rounded-0 pt-0 pb-0 pr-4 pl-4">
                    Zapisz
                </button>
            </div>


        </div>

        <div class="schedules-content">
            <div class="schedules-content-header">
                <div class="form-group row">
                    <div class="schedules-content">

                            <div class="form-group row ">
                                <label for="user"
                                       class="col-sm-6 label-size col-form-label">
                                    Wybierz Klienta
                                </label>
                                <div class="col-sm-3 ">

                                    <input list="user" name='user'>
                                    <datalist id="user">
                                        {% for user in users %}
                                            {% if user.pk == user_def %}
                                                <option value={{ user }} selected="selected">{{ user.pk }}</option>
                                            {% else %}
                                                <option value={{ user }}>{{ user.pk }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </datalist>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="meal" class="col-sm-6 label-size col-form-label">
                                    Wybierz posiłek
                                </label>
                                <div class="col-5">

                                    <input list="meal" name="meal">
                                    <datalist id="meal">
                                        {% for meal in meals %}
                                            <option value='{{ meal.meal_id }}'> {{ meal.name }} </option>
                                        {% endfor %}
                                    </datalist>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="recipe" class="col-sm-6 label-size col-form-label">
                                    Ocena:
                                </label>
                                <div class="col-sm-4">
                                    <input list="mark" name="mark">
                                    <datalist id="mark">
                                        <option value='1'>1</option>
                                        <option value='2'>2</option>
                                        <option value='3'>3</option>
                                        <option value='4'>4</option>
                                        <option value='5'>5</option>
                                    </datalist>
                                </div>


                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

BoxDiet/templates/BoxDiet/user_detail.html
{% extends "BoxDiet/__base__.html" %}
{% block title %}{% endblock title %}
{% block content %}
    <div class="dashboard-content border-dashed p-3 m-4 view-height">

        <div class="row border-bottom border-3 p-1 m-1">
            <div class="col noPadding">
                <h3 class="color-header text-uppercase">Klient</h3>
            </div>

            <div class="d-flex justify-content-end mb-2 pl-1">
                <a href="{% url 'rank_create' %}" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4">Dodaj ocenę</a>
            </div>

            <div class="d-flex justify-content-end mb-2 pl-1">
                <a href="{% url 'user_list' %}" class="btn btn-color rounded-0 pt-0 pb-0 pr-4 pl-4">Powrót</a>
            </div>
        </div>

        <div class="schedules-content">
            <div class="schedules-content-header">
                <div class="form-group row">
                                <span class="col-sm-2 label-size col-form-label">
                                    Id
                                </span>
                    <div class="col-sm-10">
                        <p class="schedules-text">{{ object.id }}</p>
                    </div>
                </div>
                <div class="form-group row">
                                <span class="col-sm-2 label-size col-form-label">
                                    Płeć
                                </span>
                    <div class="col-sm-10">
                        <p class="schedules-text">
                            {{ object.get_sex_display }}
                        </p>
                    </div>
                </div>
                 <div class="form-group row">
                                <span class="col-sm-2 label-size col-form-label">
                                    Oceny
                                </span>
                    <div class="col-sm-10">
                        <p class="schedules-text">
                            Średnia: {% if user.avg_of_given_ranks %}
                            {{ user.avg_of_given_ranks|floatformat }}
                        {% else %} Brak ocen {% endif %}
                        </p>
                        <p class="schedules-text">
                            Liczba ocen:
                            {% if user.no_of_given_ranks.mark__count %}{{ user.no_of_given_ranks.mark__count }}
                            {% else %} Brak ocen {% endif %}
                        </p>
                    </div>
            </div>
            {% for rank in object.meals_user.all %}
                <table class="table">
                <thead>
                <tr class="d-flex">
                    <th class="col-8"><a href="{% url 'meal_detail' rank.meal_id %}">{{ rank.meal }}</a></th>
                    <th class="col-2">realna ocena: {{ rank.mark }}</th>
                    <th class="col-2"></th>
                </tr>
                </thead>

            {% endfor %}
            </table>
        </div>
        <h3>Rekomendacje dla Klienta: {{ rec.id }} </h3>

        <div>
            {% for rec in recs %}
                <table class="table">
                <thead>
                <tr class="d-flex">
                    <th class="col-8"><a href='{% url 'meal_detail' rec.meal_id %}'> {{ rec.meal }}  </a></th>
                    <th class="col-2">przewidywana ocena: {{ rec.predicted_mark|floatformat}}</th>

                </tr>
                </thead>

            {% endfor %}
            </table>
        </div>
    </div>
    </div>
{% endblock content %}

BoxDiet/templates/BoxDiet/user_list.html
{% extends "BoxDiet/__base__.html" %}
{% block title %}{% endblock %}
{% block content %}
    <div class="dashboard-content border-dashed p-3 m-4 view-height">

        <div class="row border-bottom border-3 p-1 m-1">
            <div class="col noPadding">
                <h3 class="color-header text-uppercase">Klienci</h3>
            </div>
            <form method="get" action="">
            <div class="d-flex justify-content-end mb-2 pl-1">
                <input type="text" class="input rounded-0 pt-0 pb-0 pr-4 pl-4" style='width:12em'
                       name="searched_name" placeholder="Id lub płeć">
                <button type="submit" class="btn btn-warning rounded-0 pt-0 pb-0 pr-4 pl-4">Szukaj
                </button>

            </div>
            </form>
            <div class="d-flex justify-content-end mb-2 pl-1">
                <a href="{% url 'user_create' %}"
                   class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4">Dodaj
                    Klienta</a>
            </div>
            <div class="d-flex justify-content-end mb-2 pl-1">
                <a href="{% url 'rank_create' %}" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4">Dodaj
                    ocenę</a>
            </div>
        </div>

        <div class="schedules-content">
            <table class="table border-bottom">
                <thead>
                <tr class="d-flex">
                    <th class="col-2">ID</th>
                    <th class="col-2">Płeć</th>
                    <th class="col-2">Średnia</th>
                    <th class="col-2">Liczba ocen</th>
                    <th class="col-3 center">Akcje</th>
                </tr>
                </thead>
                <tbody class="text-color-lighter">


                {% for user in object_list %}
                    <tr class="d-flex">
                        <td class="col-2">{{ user.id }}</td>
                        <td class="col-2">
                            {{ user.get_sex_display }}
                        </td>
                        <td class="col-2">
                            {% if user.avg_of_given_ranks %}{{ user.avg_of_given_ranks|floatformat }}
                            {% else %} Brak ocen {% endif %}
                        <td class="col-2">
                            {% if user.no_of_given_ranks.mark__count %}{{ user.no_of_given_ranks.mark__count }}
                            {% else %} Brak ocen {% endif %}
                        <td class="col-3 d-flex align-items-center justify-content-center flex-wrap">
                            {#                            <a href="#" class="btn btn-danger rounded-0 text-light m-1">Usuń</a>#}
                            <a href="{% url 'user_detail' pk=user.id %}" class="btn btn-info rounded-0 text-light m-1">Szczegóły</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="container2">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li class="page-item">  <!-- Jump to Previous Page -->
                        {% if object_list.has_previous %}
                            <li class="previous"><a href="?page={{ object_list.previous_page_number }}&searched_name={{ searched_name }}">
                                <span aria-hidden="true"> < poprzednia &nbsp;</span></a>
                                {% else %}
                            <li class="previous disabled"><a> </a>
                        {% endif %}
                        </li>
                    {% for page in page_range %}
                        {% if page == object_list.number %}
                            <li class="pg active"><a class="page_number" href="?page={{ page }}&searched_name={{ searched_name }}">| {{ page }}</a>
                                {% else %}
                            <li class="pg"><a class="page_number" href="?page={{ page }}&searched_name={{ searched_name }}">| {{ page }}</a>
                        {% endif %}
                    {% endfor %}
                    <li class="page-item">  <!-- Jump to Next Page -->
                        {% if object_list.has_next %}
                            <li class="previous"><a href="?page={{ object_list.next_page_number }}&searched_name={{ searched_name }}">&nbsp;następna
                                ></a>
                            </li>
                        {% else %}
                            <li class="next disabled"><a> </a>
                        {% endif %}
                        </li>
                </ul>
            </nav>
        </div>
    </div>
{% endblock content %}